name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - "*"
  pull_request:

permissions:
  contents: read

jobs:
  ci-github:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # - runner: macos-13 # PyTorch compilation fails on macOS x86_64
          #   python: '3.10'
          # - runner: macos-14
          #   python: '3.10'
          - runner: ubuntu-22.04
            python: '3.10'
          # - runner: windows-2022
          #   python: '3.10'
    steps:
      - name: "Runner platform: ${{ runner.os }}-${{ runner.arch }}"
        run: echo "I'm running on ${{ runner.os }}-${{ runner.arch }}!"

      - run: echo $PATH
      # - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python }}
      #     cache: 'pip'

      # - name: Patch Dependencies for Linux
      #   if: runner.os == 'Linux'
      #   run: sudo apt-get install -y libgomp1

      # - name: Run Custom CI Scripts
      #   run: python scripts/x_ci.py

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: {{ runner.os }}-{{ runner.arch }}
      #     path: dist

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   iif: startsWith(github.ref, 'refs/tags/')
  #   needs: [ci-github]
  #   steps:
  #     - uses: actions/download-artifact@v4
  #     - name: Publish to PyPI
  #       uses: PyO3/maturin-action@v1
  #       env:
  #         MATURIN_PYPI_TOKEN: {{ secrets.PYPI_API_TOKEN }}
  #       with:
  #         command: upload
  #         args: --non-interactive --skip-existing wheels-*/*
