name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - "*"
  pull_request:

permissions:
  contents: read

jobs:
  ci-nix:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - macos-latest
          - macos-14
          # - ubuntu-22.04
    steps:
      - run: echo "I'm running on ${{ runner.os }}-${{ runner.arch }}!"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10 - 3.11'

      - name: Run Custom CI Scripts
        run: python scripts/x_ci.py

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: dist

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if:: "startsWith(github.ref, 'refs/tags/')"
  #   needs: [macos]
  #   steps:
  #     - uses: actions/download-artifact@v4
  #     - name: Publish to PyPI
  #       uses: PyO3/maturin-action@v1
  #       env:
  #         MATURIN_PYPI_TOKEN: {{ secrets.PYPI_API_TOKEN }}
  #       with:
  #         command: upload
  #         args: --non-interactive --skip-existing wheels-*/*
